# This is a basic workflow to help you get started with Actions

name: automerge

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: CI-${{github.ref}}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # fetch everything, to be able to automatically calculate changelog since last tag
          fetch-depth: 0
      - name: AutoMerge PRs
        if: success() && github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "found successful PR, attempting to merge it"
          gh pr merge --merge
