# This is a basic workflow to help you get started with Actions
name: Test Secrets

# Controls when the action will run. 
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: Test custom secrets
        run: |
          set +x
          secret1="ABC123"
          secret2="123ZXC"
          echo "::add-mask::${secret1}"
          echo "::add-mask::${secret2}"
          sleep 1
          set -x
          echo "my secret1 value is: ${secret1}"
          echo "my secret2 value is: ${secret2}"
          echo "secret1=${secret1}" >> $GITHUB_ENV
          echo "secret2=${secret2}" >> $GITHUB_ENV
      - name: Another step
        run: |
          set -x
          echo "received secret1: ${secret1}"
          echo "received secret2: ${secret2}"

